name: Build_development

on:
  workflow_dispatch:      # 支持手动一键运行
  push:
    branches: [ development ]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-esp8266:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system pioarduino
          cp ./platformio_override_sample.ini ./platformio_override.ini
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run Platform
