name: Build_development

on:
  workflow_dispatch:
  push:
    branches: [ development ]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-esp8266:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies & Create SCons Patch
        run: |
          pip install platformio
          cp ./platformio_override_sample.ini ./platformio_override.ini
          
          # 创建全局 Python 兼容模块
          mkdir -p /tmp/compat/SCons/Tool
          touch /tmp/compat/SCons/__init__.py
          touch /tmp/compat/SCons/Tool/__init__.py
          cat << 'EOF' > /tmp/compat/SCons/Tool/FortranCommon.py
          def Dialectizer(*args, **kwargs): pass
          def add_f77_to_env(*args, **kwargs): pass
          def add_f90_to_env(*args, **kwargs): pass
          def add_f95_to_env(*args, **kwargs): pass
          def add_fortran_to_env(*args, **kwargs): pass
          EOF
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONPATH: /tmp/compat
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e tasmota-CN
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tasmota-CN
          path: |
            build_output/firmware/*.bin.gz
            .pio/build/tasmota-CN/*.bin.gz
            .pio/build/tasmota-CN/*.bin
